### ISSUE TITLE
text/html attachment does not work.

### ISSUE THREAD

**Issue by osolomin90** [ryparker/jest-circus-allure-environment#155] opened 2021-02-05 14:19 UTC
## Describe the bug

When I attach html I see 'Error: Unrecognized extension: text/html' 

## To Reproduce

 'Error: Unrecognized extension: text/html'

## Expected behavior

Attachment should be added successfully.

**Comment by ryparker** [comment] 2021-02-05 15:50
Sorry to hear the change to the ContentType didn't do the trick. My guess is that it's on the AllureJS side now, but that doesn't necessarily mean we can't add the functionality. I'll take a look at it this weekend and get back to you.

**Comment by osolomin90** [comment] 2021-02-05 21:11
Thanks you in advance)

**Comment by ryparker** [comment] 2021-02-10 22:20
Ok it should be fixed in `v1.0.2`. 

[Here's the new ContentType definition](https://github.com/ryparker/jest-circus-allure-environment/blob/09983463f4943c12648d7b54aeb44d5e9ad29e25/src/jest-allure-interface.ts#L22)

Allure-JS-Commons doesn't natively support HTML as a content-type however [if a filetype is provided it takes precedence](https://github.com/allure-framework/allure-js/blob/2debbad94a8a7c5d8c88f74413ec44433a4664a8/packages/allure-js-commons/src/writers/utils.ts#L4). 

So [my solution](https://github.com/ryparker/jest-circus-allure-environment/blob/09983463f4943c12648d7b54aeb44d5e9ad29e25/src/allure-reporter.ts#L232) was to setup a condition that provides the file extension `"html"` if the attachment type is `ContentType.HTML` or `"text/html"`. 

Here's an [example of how it can be used.](https://github.com/ryparker/jest-circus-allure-environment/blob/09983463f4943c12648d7b54aeb44d5e9ad29e25/__tests__/allure-api/attachment.test.js#L18)

I'll leave this issue open until you confirm its working.

**Comment by osolomin90** [comment] 2021-02-11 10:55
Hello, unfortunately I see next error:

Error: Unrecognized extension: undefined
    at Object.typeToExtension (/Users/osolomin/JavaProjects/document-manager-deployable-unit/frontend/document-manager-spa/end-to-end-tests/node_modules/allure-js-commons/src/writers/utils.ts:31:9)
    at AllureRuntime.writeAttachment (/Users/osolomin/JavaProjects/document-manager-deployable-unit/frontend/document-manager-spa/end-to-end-tests/node_modules/allure-js-commons/src/AllureRuntime.ts:35:23)
    at AllureReporter.writeAttachment (/Users/osolomin/JavaProjects/document-manager-deployable-unit/frontend/document-manager-spa/end-to-end-tests/node_modules/jest-circus-allure-environment/src/allure-reporter.ts:233:29)
    at JestAllureInterface.attachment (/Users/osolomin/JavaProjects/document-manager-deployable-unit/frontend/document-manager-spa/end-to-end-tests/node_modules/jest-circus-allure-environment/src/jest-allure-interface.ts:185:30)
    at /Users/osolomin/JavaProjects/document-manager-deployable-unit/frontend/document-manager-spa/end-to-end-tests/rocket_lawyer/framework/utils/mailosaur.js:12:22
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at JestAllureInterface.step (/Users/osolomin/JavaProjects/document-manager-deployable-unit/frontend/document-manager-spa/end-to-end-tests/node_modules/jest-circus-allure-environment/src/jest-allure-interface.ts:129:22)
    at Object.verifyIfMailWasReceived (/Users/osolomin/JavaProjects/document-manager-deployable-unit/frontend/document-manager-spa/end-to-end-tests/rocket_lawyer/framework/utils/mailosaur.js:8:12)
    at Object.<anonymous> (/Users/osolomin/JavaProjects/document-manager-deployable-unit/frontend/document-manager-spa/end-to-end-tests/rocket_lawyer/tests/sign/SignerSignsDocument.test.js:39:21) 
    
    My allure attachment looks next:
    await allure.attachment("Mail - "+templateId, email.html.body, ContentType.HTML);
    
    and new dependency:
    "jest-circus-allure-environment": "^1.0.2",

**Comment by ryparker** [comment] 2021-03-02 18:29
Sorry for the delay, I'll have some time this weekend to dive deeper into this issue though.

Do you happen to have a public reproduction of your setup?

**Comment by ryparker** [comment] 2021-06-21 07:37
Hey @osolomin90 are you still running into this issue with the latest version of the package?

**Comment by ryparker** [comment] 2021-08-06 04:50
Closing this as i'm unable to reproduce. Feel free to reopen or create a new issue for this.

**Closed by ryparker** 2021-08-06 04:50 UTC
Labels: bug, response-requested
